from __future__ import annotations

from pathlib import Path
from typing import Protocol

from winter_cli.modules.workspace.models import (
    DiffMode,
    FeatureWorktree,
    ProjectRepository,
    PullMode,
    RepoDiffResult,
    RepoStatus,
    RepoSyncOutcome,
    StandaloneRepoStatus,
    StandaloneRepository,
    Workspace,
)


class IReadRepoRepository(Protocol):
    def get_workspace(self, root_path: Path, session_prefix: str) -> Workspace: ...
    def get_worktree_status(self, worktree: FeatureWorktree) -> RepoStatus: ...
    def get_standalone_status(self, repo: StandaloneRepository) -> StandaloneRepoStatus: ...
    def get_project_status(self, repo: ProjectRepository) -> RepoStatus: ...
    def get_diff(self, worktree: FeatureWorktree, mode: DiffMode) -> RepoDiffResult: ...


class IWriteRepoRepository(IReadRepoRepository, Protocol):
    def fetch(self, worktree: FeatureWorktree) -> None: ...
    def integrate(
        self,
        worktree: FeatureWorktree,
        target_ref: str,
        mode: PullMode,
        autostash: bool,
    ) -> RepoSyncOutcome: ...
    def sync_ff_only(self, repo: ProjectRepository) -> None: ...
    def set_upstream(self, worktree: FeatureWorktree, remote_branch: str) -> None: ...
    def unset_upstream(self, worktree: FeatureWorktree) -> None: ...
    def set_push_default(self, worktree: FeatureWorktree) -> None: ...
    def push(self, worktree: FeatureWorktree, feature_branch: str | None = None) -> int: ...
    def has_local_ref(self, worktree: FeatureWorktree, ref: str) -> bool: ...
    def is_worktree_dirty(self, worktree: FeatureWorktree) -> bool: ...
    def count_commits_not_in(self, worktree: FeatureWorktree, ref: str) -> int: ...
    def hard_reset(self, worktree: FeatureWorktree, target_ref: str) -> None: ...
    def fetch_standalone(self, repo: StandaloneRepository) -> None: ...
    def integrate_standalone(
        self,
        repo: StandaloneRepository,
        mode: PullMode,
        autostash: bool,
    ) -> RepoSyncOutcome: ...
    def push_standalone(self, repo: StandaloneRepository) -> int: ...
    def get_standalone_tracking_ahead(self, repo: StandaloneRepository) -> int: ...
    def get_standalone_upstream(self, repo: StandaloneRepository) -> str | None: ...
